# Назва нашого пайплайну, яка буде показуватись у вкладці Actions
name: Java CI/CD

# Коли запускати пайплайн:
on:
  push:                # Після пушу коду
    branches: [ main ] # ...але тільки якщо пуш у гілку main
  pull_request:        # Також при створенні pull request (наприклад, для рев'ю)

# --- CI: Збірка та тестування ---
jobs:
  build-and-test:
    name: 🧪 CI - Build & Test       # Назва job-а
    runs-on: ubuntu-latest          # Віртуальна машина Linux

    steps:
      # Крок 1: Завантаження коду з репозиторію
      - name: Checkout code
        uses: actions/upload-artifact@v4

      # Крок 2: Встановлюємо Java (тут версія 17, можна змінити на свою)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Вказуємо JDK-дистрибутив (temurin = AdoptOpenJDK)

      # Крок 3: Компілюємо, запускаємо тести, створюємо .jar
      - name: Build with Maven
        run: mvn clean install

      # Крок 4: (Необов’язковий) — Запускаємо тільки тести окремо (може дублювати попереднє)
      - name: Run Unit Tests
        run: mvn test

      # Крок 5: Архівуємо тестові звіти (наприклад, для QA або аналізу)
      - name: Archive Test Reports
        if: always()  # Виконувати навіть якщо попередній крок зафейлився
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports  # Типовий шлях для звітів Maven Surefire
